#!/bin/bash

# Extract version from gleam.toml
VERSION=$(grep '^version = ' gleam.toml | sed 's/version = "\(.*\)"/\1/')

if [ -z "$VERSION" ]; then
    echo "Error: Could not find version in gleam.toml"
    exit 1
fi

# Define the output file path
OUTPUT_FILE="src/core/version.gleam"

# Ensure the parent directory exists
mkdir -p src/core

# Generate the Gleam file
cat <<EOF > "$OUTPUT_FILE"
//// DO NOT EDIT THIS FILE MANUALLY
//// This file is auto-generated by scripts/sync_version.sh
//// based on the version specified in gleam.toml.

import gleamsver.{type SemVer}

/// The current version of the application as a string.
pub const string = "$VERSION"

/// Parses the version string and returns a \`SemVer\` type.
/// Panics if the version string is invalid (which should not happen
/// if the source gleam.toml version is valid SemVer).
pub fn get() -> SemVer {
  let assert Ok(v) = gleamsver.parse(string)
  v
}
EOF

echo "Successfully synchronized version $VERSION to $OUTPUT_FILE"
